### ISSUE TITLE
Can the Arduino code be changed over the air?

### ISSUE THREAD

**Issue by VictorMFCoelho** [aderusha/MQTTCarPresence#23]
Hi!
My D1 Mini is on a hard to reach spot, can it be accessed over the air?
I have to make changes on two devices, one I have to clear the credencials as the car will be sold and the other a have to change the node name. Can it be done over the air?
Thanks!

**Comment by aderusha** [comment]
Kinda yes but probably no.  If you compiled the code yourself and set the [otaPassword](https://github.com/aderusha/MQTTCarPresence/blob/master/MQTTCarPresence/MQTTCarPresence.ino#L5), then yes you can use the arduino Over-The-Air flash update mechanism to flash the device.  If you didn't set this value at compile time, you'll need physical access to the device.

**Comment by VictorMFCoelho** [comment]
Thanks a lot!
