### ISSUE TITLE
Wemos D1 Mini Pro - Failed to connect to ESP8266

### ISSUE THREAD

**Issue by biiiink** [aderusha/MQTTCarPresence#7]
I get this error when trying to upload this sketch to a D1 Mini Pro:

`Arduino: 1.8.10 (Mac OS X), Board: "LOLIN(WEMOS) D1 mini Pro, 80 MHz, Flash, Disabled, All SSL ciphers (most compatible), 16M (15M SPIFFS), v2 Lower Memory, Disabled, None, Only Sketch, 115200"

Sketch uses 312248 bytes (29%) of program storage space. Maximum is 1044464 bytes.
Global variables use 29952 bytes (36%) of dynamic memory, leaving 51968 bytes for local variables. Maximum is 81920 bytes.
esptool.py v2.6
2.6
esptool.py v2.6
Serial port /dev/cu.usbserial-01849A42
Connecting........_____....._____....._____....._____....._____....._____.....____Traceback (most recent call last):
  File "/Users/biiiink/Library/Arduino15/packages/esp8266/hardware/esp8266/2.5.2/tools/upload.py", line 25, in <module>
    esptool.main(fakeargs)
  File "/Users/biiiink/Library/Arduino15/packages/esp8266/hardware/esp8266/2.5.2/tools/esptool/esptool.py", line 2653, in main
    esp.connect(args.before)
  File "/Users/biiiink/Library/Arduino15/packages/esp8266/hardware/esp8266/2.5.2/tools/esptool/esptool.py", line 468, in connect
    raise FatalError('Failed to connect to %s: %s' % (self.CHIP_NAME, last_error))
esptool.FatalError: Failed to connect to ESP8266: Timed out waiting for packet header
esptool.FatalError: Failed to connect to ESP8266: Timed out waiting for packet header`

I have tried using a D1 Mini and it worked fine.  I've also tried a different D1 Mini Pro
These are the settings im using for the D1 Mini Pro
![Screen Shot 2019-10-17 at 9 52 58 AM](https://user-images.githubusercontent.com/1641304/67025853-f454d500-f0c3-11e9-9b0e-f302429de8be.png)

Any help would be greatly appreciated

**Comment by aderusha** [comment]
This error is related to the communication between your Mac and the serial interface on your WeMos D1 Mini Pro.  It could be a bad board, bad cabling, or software configuration.  You might want to check [the issues list for esptool](https://github.com/espressif/esptool/issues) for further troubleshooting help.
