### ISSUE TITLE
two WI-FI

### ISSUE THREAD

**Issue by superbosu** [aderusha/MQTTCarPresence#8]
Hi, is there a way to modify the code in order to connect to multiple wifi?
for example I have wi-fi A and wifi B, but I can configure it only for one of them.
tnx

**Comment by aderusha** [comment]
If you check out the [ESP8266WiFiMulti library example here](https://github.com/esp8266/Arduino/blob/master/libraries/ESP8266WiFi/examples/WiFiMulti/WiFiMulti.ino) you can find how that works.  You'd need to update `void setupWifi()` to utilize the new library following the example given.
